# Generated by Django 5.2.16 on 2026-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(db_index=True, help_text='OPIS Truckstop ID from the source price sheet; stable identity for a physical station.', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_gallon', models.DecimalField(decimal_places=3, max_digits=7)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(blank=True, help_text="'city_reference' if resolved from the bundled US cities dataset, else blank if unresolved.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_lat_lng_idx'), models.Index(fields=['state', 'city'], name='station_state_city_idx'), models.Index(fields=['price_per_gallon'], name='station_price_idx')],
            },
        ),
    ]
