# Generated by Django 5.2.16 on 2026-07-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('station_count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
    ]
