# Generated by Django 5.2.16 on 2026-07-20 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_query', models.CharField(max_length=255)),
                ('finish_query', models.CharField(max_length=255)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('finish_latitude', models.FloatField()),
                ('finish_longitude', models.FloatField()),
                ('distance_miles', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('geometry', models.JSONField()),
                ('vehicle_mpg', models.FloatField()),
                ('vehicle_range_miles', models.FloatField()),
                ('total_gallons', models.FloatField()),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('warning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('station_name', models.CharField(max_length=255)),
                ('station_address', models.CharField(blank=True, max_length=255)),
                ('station_city', models.CharField(max_length=120)),
                ('station_state', models.CharField(max_length=2)),
                ('station_latitude', models.FloatField()),
                ('station_longitude', models.FloatField()),
                ('distance_into_trip_miles', models.FloatField()),
                ('distance_from_route_miles', models.FloatField()),
                ('price_per_gallon', models.FloatField()),
                ('gallons_purchased', models.FloatField()),
                ('cost', models.FloatField()),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station')),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='planner.routeplan')),
            ],
            options={
                'ordering': ['route_plan', 'order'],
                'constraints': [models.UniqueConstraint(fields=('route_plan', 'order'), name='unique_stop_order_per_plan')],
            },
        ),
    ]
